### ISSUE TITLE
Can't build.

### ISSUE THREAD

**Issue by nigelgbanks** [tknerr/vagrant-managed-servers#58]
Using https://hub.docker.com/_/ruby/ I'm unable to build the plugin.

Using Ruby 2.3, and Bundler 1.7.
 
```bash
root@c7f7ac3570c7:/build# /usr/local/bundle/bin/bundle
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Your Gemfile lists the gem vagrant-managed-servers (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Updating https://github.com/mitchellh/vagrant.git
Fetching gem metadata from https://rubygems.org/..........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 11.1.2
Using builder 3.2.2
Using gyoku 1.3.1
Using mini_portile 0.6.0
Using nokogiri 1.6.3.1
Using akami 1.3.1
Using bundler 1.7.0
Using hitimes 1.2.3
Using timers 4.1.1
Using celluloid-essentials 0.20.5
Using celluloid-extras 0.20.5
Using celluloid-fsm 0.20.5
Using celluloid-pool 0.20.5
Using celluloid-supervision 0.20.5
Using celluloid 0.17.3
Using ffi 1.9.10
Using childprocess 0.5.9
Using diff-lcs 1.2.5
Using unf_ext 0.0.7.2
Using unf 0.1.4
Using domain_name 0.5.20160310
Using erubis 2.7.0
Using gssapi 1.0.3
Using hashicorp-checkpoint 0.1.4
Using http-cookie 1.0.2
Using httpclient 2.7.1
Using rack 1.6.4
Using httpi 0.9.7
Using i18n 0.6.11
Using rb-fsevent 0.9.7
Using rb-inotify 0.9.7
Using listen 2.8.6
Using little-plugger 1.1.4
Using log4r 1.1.10
Using multi_json 1.11.2
Using logging 1.8.2
Using mime-types 2.99.1
Using net-ssh 2.9.4
Using net-scp 1.1.2
Using net-sftp 2.1.2
Using netrc 0.11.0
Using nori 1.1.5
Using rb-kqueue 0.2.4
Using rest-client 1.8.0
Using rspec-core 2.14.8
Using rspec-expectations 2.14.5
Using rspec-mocks 2.14.6
Using rubyntlm 0.1.1
Using wasabi 1.0.0
Using savon 0.9.5
Using uuidtools 2.1.5
Using wdm 0.1.1
Using winrm 1.1.3

NoMethodError: undefined method `spec' for nil:NilClass
Did you mean?  inspect
An error occurred while installing vagrant (1.7.2), and Bundler cannot continue.
```

**Comment by nigelgbanks** [comment]
Can build with Bundler 1.7.15
